using Test
import Generate

module GenerateTests
    using Test
    import ..Generate

    function test_generate(fhir_release::AbstractString)
        url = "https://www.hl7.org/fhir/$(fhir_release)/definitions.json.zip"
        json_definitions = Generate.download_fhir_json_schema(url)
        schema_string = json_definitions["fhir.schema.json.zip"]["fhir.schema.json"]
        temp_dir = mktempdir(; cleanup = true)
        output_file = joinpath(temp_dir, "autogenerated.jl")
        @test !isfile(output_file)
        @test !ispath(output_file)
        Generate.output_fhir_types(; fhir_release = fhir_release, schema_string = schema_string, output_file = output_file)
        @test isfile(output_file)
        @test ispath(output_file)
        s = strip(read(output_file, String))
        @test length(s) > 10_000
        return output_file
    end

    module GenerateTests_R4
        using Test
        import ..Generate
        import ..test_generate
        output_file = test_generate("R4")
        @test !(@isdefined R4Types)
        # include(output_file)
        # @test (@isdefined R4Types)
    end
    module GenerateTests_STU3
        using Test
        import ..Generate
        import ..test_generate
        # output_file = test_generate("STU3")
        @test !(@isdefined STU3Types)
        # include(output_file)
        # @test (@isdefined STU3Types)
    end
end # end module GenerateTests
