import Generate

fhir_versions = [:R4]

for fhir_version in fhir_versions
    url = "https://www.hl7.org/fhir/$(fhir_version)/definitions.json.zip"
    json_definitions = Generate.download_fhir_json_schema(url)
    schema_string = json_definitions["fhir.schema.json.zip"]["fhir.schema.json"]
    output_file = joinpath(
        dirname(dirname(@__DIR__)),
        "src",
        "autogenerated",
        "autogenerated-$(fhir_version).jl",
    )
    Generate.output_fhir_types(; schema_string = schema_string, output_file = output_file)
end
