import .JSON3

"""
FHIR version R4.

## Summary
abstract type Authentication <: Any
"""
struct R4 <: FHIRVersion
end

module R4Types
import ..JSON3
include("autogenerated/autogenerated-R4.jl")
end # end module R4Types
