export R4
export R4Types

"""
FHIR version R4.

## Summary
abstract type Authentication <: Any
"""
struct R4 <: FHIRVersion
end

module R4Types
include("autogenerated/autogenerated-R4.jl")
end # end module R4Types
