name: Fix format
on:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: all builds except for builds on the `master` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
permissions:
  contents: write
  pull-requests: write
jobs:
  fix-format:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: true # we intentionally set this to true, since we plan on committing and pushing later
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - run: make format-fix
      - name: Create pull request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          commit-message: "🤖 Automatic code formatting"
          title: "🤖 Automatic code formatting"
          body: |
            This pull request fixes the code formatting of the Julia files in branch ${{ github.ref_name }}.

            Auto-generated by [create-pull-request][1].
  
            [1]: https://github.com/peter-evans/create-pull-request
          branch: create-pull-request/fixformat/${{ github.ref_name }}
          delete-branch: true
